# Site settings
title: H's Blog
author: Hadi Moshayedi
author_avatar: https://avatars1.githubusercontent.com/u/628106?v=3&u=fb247a9f57cd3831c66e52bcc922d2c2a9868130&s=140
email: hadi@moshayedi.net
description: Blog about whatever.
baseurl: "" # optional
url: "https://pykello.github.io"
twitter_username: pykello
github_username: pykello
github_repo: pykello/pykello.github.io
google_analytics: 'UA-71312421-1'
disqus: pykello

# Build settings
markdown: kramdown
permalink: pretty
excerpt_separator: "<!-- more -->"

gems:
  - jekyll-sitemap
